name = "MID"
uuid = "864cfd1d-2a39-4b19-8808-16c25e50ed02"
version = "1.0.0-DEV"
authors = ["Matthew Thomas <60493847+Syndrius@users.noreply.github.com> and contributors"]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Arpack = "=0.5.3"
FunctionWrappers = "1.1.3"
JLD2 = "0.6.2"
julia = "1.10.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
